[manager]
manager ansible_host=54.86.208.143 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/terraform-key.pem

[workers]
worker-a ansible_host=18.211.165.39 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/terraform-key.pem
worker-b ansible_host=100.24.238.89 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/terraform-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
